# TODO: NIY
ignore-small = { w = 1024, h = 1024 }

[markers]
disk = [
  'd:\backer-id.json',
  'c:\fotki\backer-id.json'
]
ipfs = [ ]

[[date-path. "sf7-c-fotki"]]
path = '/(20\d\d)(\d\d)(\d\d)_(\d\d)(\d\d)(\d\d)\.jpg'
date = '$1-$2-$3 $4:$5:$6'

[[date-path. "sf7-c-fotki"]]
path = '/(20\d\d)-(\d\d)-(\d\d) (\d\d)\.(\d\d)\.(\d\d)\.jpg'
date = '$1-$2-$3 $4:$5:$6'

[[date-path. "sf7-c-fotki"]]
path = '/IMG_(20\d\d)(\d\d)(\d\d)_(\d\d)(\d\d)(\d\d)\.jpg'
date = '$1-$2-$3 $4:$5:$6'

[[date-path. "sf7-c-fotki"]]
path = '/signal-(20\d\d)-(\d\d)-(\d\d)-(\d\d)(\d\d)(\d\d)(-\d*)?\.jpg'
date = '$1-$2-$3 $4:$5:$6'

[[date-path. "sf7-c-fotki"]]
path = '/P_(20\d\d)(\d\d)(\d\d)_(\d\d)(\d\d)(\d\d)\.jpg'
date = '$1-$2-$3 $4:$5:$6'

[[date-path. "sf7-c-fotki"]]
path = '/IMG-(20\d\d)(\d\d)(\d\d)-WA\d\d\d\d\.jpe?g'
date = '$1-$2-$3'

[[date-path. "sf7-c-fotki"]]
path = '/IMG-(20\d\d)(\d\d)(\d\d)-0\d\d\d\d.jpg'
date = '$1-$2-$3'
