[package]
name = "backer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
globwalk = "0.8.1"
image = { version = "0.23", default-features = false, features = ["jpeg_rayon"] }
kamadak-exif = "0.5"
rusqlite = { version = "0.25", features = ["bundled"] }
sha-1 = "0.9"
